# frozen_string_literal: true

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'rails-stimulus-tailwind_development')  %>

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'rails-stimulus-tailwind_test')  %>

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'rails-stimulus-tailwind_production')  %>
